name: Swift

on:
  push:
    branches: [ development ]
  pull_request:
    branches: [ development ]

jobs:
  build:

    runs-on: macos-latest
    
    strategy:
      fail-fast: false
      matrix:
        xcode: ["12.4"]


    steps:
    - uses: actions/checkout@v2
    
    - name: Setup Xcode version
      uses: maxim-lobanov/setup-xcode@v1.2.3
      with: 
        xcode-version: '${{ matrix.xcode }}'
        
    - name: Cache SwiftPM
      uses: actions/cache@v1
      with:
        path: .build
        key: ${{ runner.os }}-xcode_${{ matrix.xcode }}-swiftpm-deps-${{ github.workspace }}-${{ hashFiles('Package.resolved') }}
        restore-keys: |
            ${{ runner.os }}-xcode_${{ matrix.xcode }}-swiftpm-deps-${{ github.workspace }}
            
    - name: SwiftPM tests
      run: swift test --enable-code-coverage

    - name: Convert coverage to lcov
      run: xcrun llvm-cov export -format="lcov" .build/debug/HaloCoreDataPackageTests.xctest/Contents/MacOS/HaloCoreDataTests -instr-profile .build/debug/codecov/default.profdata > coverage.lcov

    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v1
      with:
        fail_ci_if_error: true
        
