name: Swift

on:
  push:
    branches: [ development ]
  pull_request:
    branches: [ development ]

jobs:
  build:

    runs-on: macos-latest
    
    strategy:
      fail-fast: false
      matrix:
        xcode: ["12.5"]


    steps:
    - uses: actions/checkout@v2
    
    - name: Select Xcode ${{ matrix.xcode }}
      run: sudo xcode-select --switch /Applications/Xcode_${{ matrix.xcode }}.app
        
    - name: Build
      run: swift build -v
    - name: Run tests
      run: swift test -v
