name: Swift

on:
  push:
    branches: [ development ]
  pull_request:
    branches: [ development ]

jobs:
  build:

    runs-on: macos-latest
    
    strategy:
      fail-fast: false
      matrix:
        xcode: ["12.5"]


    steps:
    - uses: actions/checkout@v2
    
    - name: Setup Xcode version
      uses: maxim-lobanov/setup-xcode@v1.2.3
      with: 
        xcode-version: '12.5'
        
    - name: Build
      run: swift build -v
    - name: Run tests
      run: swift test -v
